services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    networks:
      - chismepress-net

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    networks:
      - chismepress-net

networks:
  chismepress-net:
    driver: bridge
